services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rewards"
    ports:
      - 5432:5432  
    networks:
      - app-network  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

